function [wellSol, states] = gen_simulation(G, rock, fluid, initState, schedule)
    %% Simulation
    lsolve  = BackslashSolverAD('maxIterations',500,'tolerance',1e-3);
    csolve  = CPRSolverAD('maxIterations',500,'tolerance',1e-3);
    nlsolve = NonLinearSolver('useRelaxation'          , true , ...
                              'maxIterations'          , 200  , ...
                              'maxTimestepCuts'        , 10   , ...
                              'useLinesearch'          , true , ...
                              'linesearchMaxIterations', 10   , ...
                              'LinearSolver'           , lsolve);

    model = TwoPhaseWaterGasModel(G, rock, fluid, 0, 0);
    [wellSol, states] = simulateScheduleAD(initState, model, schedule, ...
                                           'NonLinearSolver', nlsolve);

end