function [W] = gen_wells_3d(G, rock, inj_loc, z_layers, irate)
W = [];
W = verticalWell(W, G, rock, ...
                inj_loc(1), inj_loc(2), z_layers(1):z_layers(2),...
                'Type',         'rate', ...
                'Val',          irate, ...
                'InnerProduct', 'ip_tpf', ...
                'Radius',       0.05, ...
                'Comp_i',       [0 1], ...
                'name',         'Injector');
end

