function W = make_wells(W,G,rock,well_locs,inj_rate,max_bhp)
% Setup the well(s)
    num_wells = length(well_locs);
    for i=1:num_wells
        W = addWell(W, G, rock, well_locs(i), ...
                    'name', ['Injector', int2str(i)], ...
                    'sign', 1, ...
                    'InnerProduct', 'ip_tpf', ...
                    'type', 'rate', ...
                    'val', inj_rate / num_wells, ...
                    'lims', max_bhp, ...
                    'comp_i', [0 1]);
    end
end