function [W] = gen_wells_3d(G, rock, inj_loc, nz, irate)
W = [];
W = verticalWell(W, G, rock, inj_loc(1), inj_loc(2), nz-1:nz,...
                'Type', 'rate', ...
                'Val', irate, ...
                'InnerProduct', 'ip_tpf', ...
                'Radius', 0.05, ...
                'Comp_i', [0 1], ...
                'name', 'Injector');
end

