function [props] = gen_props()

    g       = gravity;
    rhow    = 1000;                                   % water density (kg/m^3)
    co2     = CO2props();                             % CO2 property functions
    p_ref   = 30 *mega*Pascal;                        % reference pressure
    t_ref   = 94+273.15;                              % reference temperature
    co2_rho = co2.rho(p_ref, t_ref);                  % CO2 density
    co2_c   = co2.rhoDP(p_ref, t_ref) / co2_rho;      % CO2 compressibility
    wat_c   = 0;                                      % water compressibility
    c_rock  = 4.35e-5 / barsa;                        % rock compressibility
    srw     = 0.27;                                   % residual water
    src     = 0.20;                                   % residual CO2
    pe      = 5 * kilo * Pascal;                      % capillary entry pressure
    muw     = 8e-4 * Pascal * second;                 % brine viscosity
    muco2   = co2.mu(p_ref, t_ref) * Pascal * second; % co2 viscosity
    
    props   = struct('g',       g       , ...
                     'rhow',    rhow    , ...
                     'co2',     co2     , ...
                     'p_ref',   p_ref   , ...
                     't_ref',   t_ref   , ...
                     'co2_rho', co2_rho , ...
                     'co2_c',   co2_c   , ...
                     'wat_c',   wat_c   , ...
                     'c_rock',  c_rock  , ...
                     'srw',     srw     , ...
                     'src',     src     , ...
                     'pe',      pe      , ...
                     'muw',     muw     , ...
                     'muco2',   muco2);

end