function [wellSol, states, model] = gen_simulation(Gt, rock2D, fluid, initState, schedule)
    % Create and simulate model
    lsolve  = BackslashSolverAD('maxIterations',500,'tolerance',1e-3);
    csolve  = CPRSolverAD('maxIterations',500,'tolerance',1e-3);
    nlsolve = NonLinearSolver('useRelaxation'          , true , ...
                              'maxIterations'          , 200  , ...
                              'maxTimestepCuts'        , 10   , ...
                              'useLinesearch'          , true , ...
                              'linesearchMaxIterations', 10   , ...
                              'LinearSolver'           , lsolve);

    model = CO2VEBlackOilTypeModel(Gt, rock2D, fluid);
    [wellSol, states] = simulateScheduleAD(initState, model, schedule, ...
                                           'NonLinearSolver', nlsolve);
    states = [{initState} states(:)'];
end

