function [fluid] = gen_fluid(Gt, rock, props, transMult)
    
    % uses CO2 saturation
    invPc3D = @(pc) (1-props.srw) .* (props.pe ./ max(pc, props.pe)).^2 + props.srw;
    kr3D    = @(s) max((s-props.src) ./ (1-props.src), 0).^2; 

    fluid   = makeVEFluid(Gt, rock, 'P-scaled table'          , ...
                   'co2_mu_ref'  , props.muco2                , ...
                   'wat_mu_ref'  , props.muw                  , ...
                   'co2_rho_ref' , props.co2_rho              , ...
                   'wat_rho_ref' , props.rhow                 , ...
                   'co2_rho_pvt' , [props.co2_c, props.p_ref] , ...
                   'wat_rho_pvt' , [props.wat_c, props.p_ref] , ...
                   'residual'    , [props.srw, props.src]     , ...
                   'pvMult_p_ref', props.p_ref                , ...
                   'pvMult_fac'  , props.c_rock               , ...
                   'invPc3D'     , invPc3D                    , ...
                   'kr3D'        , kr3D                       , ...
                   'transMult'   , transMult);
end